export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOAD_PERSONNEL = 'LOAD_PERSONNEL';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERR_MSG = 'CLEAR_ERR_MSG';
export const GET_TODAY_LEAVES = 'GET_TODAY_LEAVES';
export const LEAVE_ERROR = 'LEAVE_ERROR';